name = "hermes"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "hermes-db"
database_id = "hermes-db-preview"
migrations_dir = "migrations"