name: Update Coverage Badge

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(grep -oP 'class="strong">\K\d+\.\d+(?=% </span>\s*<span class="quiet">Lines)' coverage/index.html | head -1)
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Coverage: $COVERAGE%"

      - name: Determine badge color
        id: badge-color
        run: |
          COVERAGE=${{ steps.coverage.outputs.percentage }}
          if (( $(echo "$COVERAGE > 80" | bc -l) )); then
            echo "color=brightgreen" >> $GITHUB_OUTPUT
          elif (( $(echo "$COVERAGE > 60" | bc -l) )); then
            echo "color=yellow" >> $GITHUB_OUTPUT
          else
            echo "color=red" >> $GITHUB_OUTPUT
          fi

      - name: Update coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 006ec188c8a105fe69bcba8097fd8bf7
          filename: hermes-coverage.json
          label: coverage
          message: ${{ steps.coverage.outputs.percentage }}%
          color: ${{ steps.badge-color.outputs.color }}
